/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cowin.main.gui;

import com.cowin.main.Application.ChangePasswordApp;
import javax.swing.JOptionPane;

/**
 *
 * @author mahesh
 */
public class ChangePassword extends javax.swing.JFrame {

    /**
     * Creates new form ChangePassword
     */
    public String OTP=null;
    ChangePasswordApp capp=null;
    public ChangePassword() {
        initComponents();
        capp = new ChangePasswordApp(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        aadhar_no = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        utype = new javax.swing.JComboBox<>();
        exit_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        otp = new javax.swing.JTextField();
        otp_btn = new javax.swing.JButton();
        password_txt = new javax.swing.JLabel();
        conf_password_txt = new javax.swing.JLabel();
        validate_btn = new javax.swing.JButton();
        submit_btn = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        conf_password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("aakar", 1, 36)); // NOI18N
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(782, 12, -1, -1));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("aakar", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User Type:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 140, 40));

        aadhar_no.setFont(new java.awt.Font("aakar", 1, 20)); // NOI18N
        aadhar_no.setForeground(new java.awt.Color(102, 102, 255));
        jPanel2.add(aadhar_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 310, 40));

        jLabel3.setFont(new java.awt.Font("aakar", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Aadhar No.:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 140, 40));

        utype.setFont(new java.awt.Font("aakar", 1, 20)); // NOI18N
        utype.setForeground(new java.awt.Color(102, 102, 255));
        utype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select User Type", "Vaccinator", "Vaccinee" }));
        jPanel2.add(utype, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 310, 40));

        exit_btn.setBackground(new java.awt.Color(240, 37, 55));
        exit_btn.setFont(new java.awt.Font("aakar", 1, 20)); // NOI18N
        exit_btn.setForeground(new java.awt.Color(255, 255, 255));
        exit_btn.setText("Exit");
        exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btnActionPerformed(evt);
            }
        });
        jPanel2.add(exit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 540, 140, 40));

        jLabel4.setFont(new java.awt.Font("aakar", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Enter OTP:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 140, 40));

        otp.setFont(new java.awt.Font("aakar", 1, 20)); // NOI18N
        otp.setForeground(new java.awt.Color(102, 102, 255));
        jPanel2.add(otp, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 120, 40));

        otp_btn.setBackground(new java.awt.Color(16, 193, 33));
        otp_btn.setFont(new java.awt.Font("aakar", 1, 20)); // NOI18N
        otp_btn.setForeground(new java.awt.Color(255, 255, 255));
        otp_btn.setText("Get OTP");
        otp_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otp_btnActionPerformed(evt);
            }
        });
        jPanel2.add(otp_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 120, 40));

        password_txt.setFont(new java.awt.Font("aakar", 1, 20)); // NOI18N
        password_txt.setForeground(new java.awt.Color(255, 255, 255));
        password_txt.setText("Password:");
        jPanel2.add(password_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 140, 40));

        conf_password_txt.setFont(new java.awt.Font("aakar", 1, 20)); // NOI18N
        conf_password_txt.setForeground(new java.awt.Color(255, 255, 255));
        conf_password_txt.setText("Confirm Password:");
        jPanel2.add(conf_password_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 170, 40));

        validate_btn.setBackground(new java.awt.Color(16, 193, 33));
        validate_btn.setFont(new java.awt.Font("aakar", 1, 20)); // NOI18N
        validate_btn.setForeground(new java.awt.Color(255, 255, 255));
        validate_btn.setText("Validate");
        validate_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validate_btnActionPerformed(evt);
            }
        });
        jPanel2.add(validate_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 140, 40));

        submit_btn.setBackground(new java.awt.Color(16, 193, 33));
        submit_btn.setFont(new java.awt.Font("aakar", 1, 20)); // NOI18N
        submit_btn.setForeground(new java.awt.Color(255, 255, 255));
        submit_btn.setText("Submit");
        submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btnActionPerformed(evt);
            }
        });
        jPanel2.add(submit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, 140, 40));

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 290, 40));
        jPanel2.add(conf_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 290, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 620, 640));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 730));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void otp_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otp_btnActionPerformed
        // TODO add your handling code here:
        
        if(aadhar_no.getText().equals("")|| utype.getSelectedItem().equals("Select User Type"))
        {
            JOptionPane.showMessageDialog(new javax.swing.JFrame(),"Please Enter all the fields Properly....","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else
        {
             if(capp.getOtp(aadhar_no.getText(),(String)utype.getSelectedItem()))
             {
                 JOptionPane.showMessageDialog(new javax.swing.JFrame(),"OTP send Successfully Check your SMS.","Success",JOptionPane.INFORMATION_MESSAGE);
             }
             else
             {
                 JOptionPane.showMessageDialog(new javax.swing.JFrame(),"Error While Sending OTP.\n Try after some time...","Error",JOptionPane.ERROR_MESSAGE);
             }
        }
    }//GEN-LAST:event_otp_btnActionPerformed

    private void validate_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validate_btnActionPerformed
        // TODO add your handling code here:
        if(otp.getText().equals(""))
        {
            JOptionPane.showMessageDialog(new javax.swing.JFrame(),"Please Enter all the fields Properly....","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            if(capp.validateOTP(otp.getText()))
            {
                JOptionPane.showMessageDialog(new javax.swing.JFrame(),"OTP verified Successfully......","Success",JOptionPane.INFORMATION_MESSAGE);
                password.setVisible(true);
                conf_password.setVisible(true);
                password_txt.setVisible(true);
                conf_password_txt.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(new javax.swing.JFrame(),"Wrong OTP.....","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_validate_btnActionPerformed

    private void exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_exit_btnActionPerformed

    private void submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btnActionPerformed
        // TODO add your handling code here:
        if(password.getText().equals("")|| conf_password.getText().equals("")||aadhar_no.getText().equals(""))
        {
            JOptionPane.showMessageDialog(new javax.swing.JFrame(),"Please Enter all the fields Properly....","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            if(password.getText().equals(conf_password.getText()))
            {
                if(capp.changePass(password.getText(),aadhar_no.getText()))
                {
                    JOptionPane.showMessageDialog(new javax.swing.JFrame(),"Password Changed Successfully......","Success",JOptionPane.INFORMATION_MESSAGE);
                    this.setVisible(false);
                    new Login().setVisible(true);
                }
                else
                {
                    JOptionPane.showMessageDialog(new javax.swing.JFrame(),"Error while updating password.....","Error",JOptionPane.ERROR_MESSAGE);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(new javax.swing.JFrame(),"Password and Confirm Password are not same....","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_submit_btnActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed
    public void setVisibility()
    {
        password.setVisible(false);
        conf_password.setVisible(false);
        password_txt.setVisible(false);
        conf_password_txt.setVisible(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChangePassword cp = new ChangePassword();
                cp.setVisibility();
                cp.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aadhar_no;
    private javax.swing.JPasswordField conf_password;
    private javax.swing.JLabel conf_password_txt;
    private javax.swing.JButton exit_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField otp;
    private javax.swing.JButton otp_btn;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel password_txt;
    private javax.swing.JButton submit_btn;
    private javax.swing.JComboBox<String> utype;
    private javax.swing.JButton validate_btn;
    // End of variables declaration//GEN-END:variables
}
