/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cowin.main.gui;

import com.cowin.main.Application.VaccineeApp;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author mahesh
 */
public class Vaccinee extends javax.swing.JFrame {

    /**
     * Creates new form Vaccinee
     */
    public String user_name;
    VaccineeApp vapp;
    public Vaccinee() {
        initComponents();
        vapp = new VaccineeApp(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        left_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        book_appointment_btn = new javax.swing.JButton();
        view_details_btn = new javax.swing.JButton();
        top_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logout_btn = new javax.swing.JButton();
        bottom_pannel = new javax.swing.JPanel();
        appoint_slot_panel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        select_date = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        select_vaccinator = new javax.swing.JComboBox<>();
        submit_btn = new javax.swing.JButton();
        clear_btn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        select_slot = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        get_vaccinator_btn = new javax.swing.JButton();
        get_slot_btn = new javax.swing.JButton();
        vaccination_details_panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ano = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        d1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        d2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        left_panel.setBackground(new java.awt.Color(102, 102, 255));
        left_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cowin_small.jpg"))); // NOI18N
        left_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 270));

        book_appointment_btn.setBackground(new java.awt.Color(150, 150, 255));
        book_appointment_btn.setFont(new java.awt.Font("aakar", 1, 24)); // NOI18N
        book_appointment_btn.setForeground(new java.awt.Color(255, 255, 255));
        book_appointment_btn.setText("Book Appointment");
        book_appointment_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                book_appointment_btnMouseClicked(evt);
            }
        });
        left_panel.add(book_appointment_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 340, 50));

        view_details_btn.setBackground(new java.awt.Color(150, 150, 255));
        view_details_btn.setFont(new java.awt.Font("aakar", 1, 24)); // NOI18N
        view_details_btn.setForeground(new java.awt.Color(255, 255, 255));
        view_details_btn.setText("View Details");
        view_details_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_details_btnActionPerformed(evt);
            }
        });
        left_panel.add(view_details_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 340, 340, 50));

        getContentPane().add(left_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 710));

        top_panel.setBackground(new java.awt.Color(102, 102, 255));
        top_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("aakar", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        top_panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 10, -1, -1));

        logout_btn.setBackground(new java.awt.Color(206, 17, 17));
        logout_btn.setFont(new java.awt.Font("aakar", 1, 24)); // NOI18N
        logout_btn.setForeground(new java.awt.Color(255, 255, 255));
        logout_btn.setText("LogOut");
        logout_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logout_btn.setBorderPainted(false);
        logout_btn.setFocusPainted(false);
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });
        top_panel.add(logout_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 190, 60));

        getContentPane().add(top_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 1070, 100));

        bottom_pannel.setBackground(new java.awt.Color(255, 255, 255));
        bottom_pannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        appoint_slot_panel.setBackground(new java.awt.Color(150, 150, 255));
        appoint_slot_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("aakar", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Vaccinator:");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        appoint_slot_panel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 210, 40));

        select_date.setBackground(new java.awt.Color(255, 255, 255));
        select_date.setForeground(new java.awt.Color(150, 150, 255));
        select_date.setDateFormatString("d-MM-yyyy");
        select_date.setFont(new java.awt.Font("aakar", 1, 20)); // NOI18N
        appoint_slot_panel.add(select_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 400, 40));

        jLabel14.setFont(new java.awt.Font("aakar", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Vaccine Slot:");
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        appoint_slot_panel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 210, 40));

        select_vaccinator.setBackground(new java.awt.Color(255, 255, 255));
        select_vaccinator.setFont(new java.awt.Font("aakar", 1, 20)); // NOI18N
        select_vaccinator.setForeground(new java.awt.Color(150, 150, 255));
        select_vaccinator.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Vaccinator" }));
        appoint_slot_panel.add(select_vaccinator, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 400, 40));

        submit_btn.setBackground(new java.awt.Color(10, 190, 46));
        submit_btn.setFont(new java.awt.Font("aakar", 1, 24)); // NOI18N
        submit_btn.setForeground(new java.awt.Color(255, 255, 255));
        submit_btn.setText("Submit");
        submit_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        submit_btn.setBorderPainted(false);
        submit_btn.setFocusPainted(false);
        submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btnActionPerformed(evt);
            }
        });
        appoint_slot_panel.add(submit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 190, 60));

        clear_btn.setBackground(new java.awt.Color(206, 17, 17));
        clear_btn.setFont(new java.awt.Font("aakar", 1, 24)); // NOI18N
        clear_btn.setForeground(new java.awt.Color(255, 255, 255));
        clear_btn.setText("Clear");
        clear_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clear_btn.setBorderPainted(false);
        clear_btn.setFocusPainted(false);
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });
        appoint_slot_panel.add(clear_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, 190, 60));

        jLabel15.setFont(new java.awt.Font("aakar", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Appoint Slot");
        appoint_slot_panel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 990, 60));

        jLabel16.setFont(new java.awt.Font("aakar", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Vaccination Date:");
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        appoint_slot_panel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 210, 40));

        select_slot.setBackground(new java.awt.Color(255, 255, 255));
        select_slot.setFont(new java.awt.Font("aakar", 1, 20)); // NOI18N
        select_slot.setForeground(new java.awt.Color(150, 150, 255));
        select_slot.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Slot" }));
        appoint_slot_panel.add(select_slot, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 400, 40));

        jLabel17.setFont(new java.awt.Font("aakar", 1, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("_____________________________________________________________");
        appoint_slot_panel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 990, -1));

        get_vaccinator_btn.setBackground(new java.awt.Color(10, 190, 46));
        get_vaccinator_btn.setFont(new java.awt.Font("aakar", 1, 24)); // NOI18N
        get_vaccinator_btn.setForeground(new java.awt.Color(255, 255, 255));
        get_vaccinator_btn.setText("Get Vaccinator");
        get_vaccinator_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        get_vaccinator_btn.setBorderPainted(false);
        get_vaccinator_btn.setFocusPainted(false);
        get_vaccinator_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_vaccinator_btnActionPerformed(evt);
            }
        });
        appoint_slot_panel.add(get_vaccinator_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 230, 170, 40));

        get_slot_btn.setBackground(new java.awt.Color(10, 190, 46));
        get_slot_btn.setFont(new java.awt.Font("aakar", 1, 24)); // NOI18N
        get_slot_btn.setForeground(new java.awt.Color(255, 255, 255));
        get_slot_btn.setText("Get Slot");
        get_slot_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        get_slot_btn.setBorderPainted(false);
        get_slot_btn.setFocusPainted(false);
        get_slot_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_slot_btnActionPerformed(evt);
            }
        });
        appoint_slot_panel.add(get_slot_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 160, 130, 40));

        bottom_pannel.add(appoint_slot_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 990, 530));

        vaccination_details_panel.setBackground(new java.awt.Color(150, 150, 255));
        vaccination_details_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vaccination Details:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("aakar", 1, 36), new java.awt.Color(255, 255, 255))); // NOI18N
        vaccination_details_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("aakar", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Aadhar No.:");
        vaccination_details_panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 210, 59));

        ano.setFont(new java.awt.Font("aakar", 1, 20)); // NOI18N
        ano.setForeground(new java.awt.Color(255, 255, 255));
        vaccination_details_panel.add(ano, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 570, 59));

        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setFont(new java.awt.Font("aakar", 1, 20)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        vaccination_details_panel.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 570, 59));

        jLabel6.setFont(new java.awt.Font("aakar", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Name:");
        vaccination_details_panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 210, 59));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("aakar", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("1st Does and Date:");
        vaccination_details_panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 210, 59));

        d1.setFont(new java.awt.Font("aakar", 1, 20)); // NOI18N
        d1.setForeground(new java.awt.Color(255, 255, 255));
        vaccination_details_panel.add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 570, 59));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("aakar", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("2nd Does and Date:");
        vaccination_details_panel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 210, 59));

        d2.setFont(new java.awt.Font("aakar", 1, 20)); // NOI18N
        d2.setForeground(new java.awt.Color(255, 255, 255));
        vaccination_details_panel.add(d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 570, 59));

        bottom_pannel.add(vaccination_details_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 990, 530));

        getContentPane().add(bottom_pannel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 1070, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void book_appointment_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book_appointment_btnMouseClicked
        // TODO add your handling code here:
        vaccination_details_panel.setVisible(false);
        appoint_slot_panel.setVisible(true);
    }//GEN-LAST:event_book_appointment_btnMouseClicked

    private void view_details_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_details_btnActionPerformed
        // TODO add your handling code here:
        appoint_slot_panel.setVisible(false);
        vaccination_details_panel.setVisible(true);
        List<String> l = vapp.getVaccinationDetails();
        if(l != null)
        {
            name.setText(l.get(0));
            ano.setText(l.get(1));
            d1.setText(l.get(2));
            d2.setText(l.get(3));
        }
        
    }//GEN-LAST:event_view_details_btnActionPerformed

    private void submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btnActionPerformed
        // TODO add your handling code here:
        if(select_date.getDate()==null|| select_slot.getSelectedItem().equals("Select Slot")||select_vaccinator.getSelectedItem().equals("Select Vaccinator"))
        {
            JOptionPane.showMessageDialog(new javax.swing.JFrame(),"Please Enter all the fields Properly....","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            if(vapp.setAppointedData(select_date.getDate(),(String)select_slot.getSelectedItem(),(String)select_vaccinator.getSelectedItem()))
            {
                JOptionPane.showMessageDialog(new javax.swing.JFrame(),"Successfully Added Appointment... \nYou can login now","Success",JOptionPane.INFORMATION_MESSAGE);
                select_date.setDate(null);
                select_slot.removeAllItems();
                select_vaccinator.removeAllItems();
                select_slot.addItem("Select Slot");
                select_slot.setSelectedItem("Select Slot");
                select_vaccinator.addItem("Select Vaccinator");
                select_vaccinator.setSelectedItem("Select Vaccinator");
            }
            else
            {
                JOptionPane.showMessageDialog(new javax.swing.JFrame(),"Error While Adding Appointment...\n Try after some time...","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_submit_btnActionPerformed

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        // TODO add your handling code here:
        select_date.setDate(null);
        select_slot.removeAllItems();
        select_vaccinator.removeAllItems();
        select_slot.addItem("Select Slot");
        select_slot.setSelectedItem("Select Slot");
        select_vaccinator.addItem("Select Vaccinator");
        select_vaccinator.setSelectedItem("Select Vaccinator");
    }//GEN-LAST:event_clear_btnActionPerformed

    private void get_vaccinator_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_vaccinator_btnActionPerformed
        // TODO add your handling code here:
        if(select_date.getDate() == null || select_slot.getSelectedItem().equals("Select Slot"))
        {
            
        }
        else
        {
        List<String> l = vapp.getVaccinator(select_date.getDate(),(String)select_slot.getSelectedItem());
        select_vaccinator.removeAllItems();
        for(String s : l)
        {
            select_vaccinator.addItem(s);
        }
        select_vaccinator.setSelectedItem("Select Vaccinator");
        }
    }//GEN-LAST:event_get_vaccinator_btnActionPerformed

    private void get_slot_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_slot_btnActionPerformed
        // TODO add your handling code here:
        if(select_date.getDate() == null)
        {
            
        }
        else
        {
        List<String> l = vapp.getSlot(select_date.getDate());
        select_slot.removeAllItems();
        for(String s : l)
        {
            select_slot.addItem(s);
        }
        select_slot.setSelectedItem("Select Slot");
        }
    }//GEN-LAST:event_get_slot_btnActionPerformed

    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_logout_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vaccinee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vaccinee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vaccinee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vaccinee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Vaccinee v = new Vaccinee();
                v.user_name = args[0];
                v.appoint_slot_panel.setVisible(false);
                v.vaccination_details_panel.setVisible(true);
                v.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ano;
    private javax.swing.JPanel appoint_slot_panel;
    private javax.swing.JButton book_appointment_btn;
    private javax.swing.JPanel bottom_pannel;
    private javax.swing.JButton clear_btn;
    private javax.swing.JLabel d1;
    private javax.swing.JLabel d2;
    private javax.swing.JButton get_slot_btn;
    private javax.swing.JButton get_vaccinator_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel left_panel;
    private javax.swing.JButton logout_btn;
    private javax.swing.JLabel name;
    private com.toedter.calendar.JDateChooser select_date;
    private javax.swing.JComboBox<String> select_slot;
    private javax.swing.JComboBox<String> select_vaccinator;
    private javax.swing.JButton submit_btn;
    private javax.swing.JPanel top_panel;
    private javax.swing.JPanel vaccination_details_panel;
    private javax.swing.JButton view_details_btn;
    // End of variables declaration//GEN-END:variables
}
