/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cowin.main.gui;

import com.cowin.db.DBConnection;
import com.cowin.main.Application.VaccinatorApp;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mahesh
 */
public class Vaccinator extends javax.swing.JFrame {

    /**
     * Creates new form Vaccinator
     */
    public String user_name;
    VaccinatorApp vapp ;
    public Vaccinator() {
        initComponents();
        vapp = new VaccinatorApp(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        left_panel = new javax.swing.JPanel();
        appinted_vaccinee_btn = new javax.swing.JButton();
        schedule_vaccination_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        top_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logout_btn = new javax.swing.JButton();
        bottom_panel = new javax.swing.JPanel();
        schedule_appointment_slot_panel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        submit_btn = new javax.swing.JButton();
        cancel_btn = new javax.swing.JButton();
        vac_date = new com.toedter.calendar.JDateChooser();
        vac_time = new javax.swing.JComboBox<>();
        appointed_vaccinee_panel = new javax.swing.JPanel();
        appointed_table = new javax.swing.JScrollPane();
        table_appointed = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        find_btn = new javax.swing.JButton();
        aadhar_no_find = new javax.swing.JTextField();
        vaccinated_btn = new javax.swing.JButton();
        vaccine_name = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        left_panel.setBackground(new java.awt.Color(102, 102, 255));
        left_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        appinted_vaccinee_btn.setBackground(new java.awt.Color(150, 150, 255));
        appinted_vaccinee_btn.setFont(new java.awt.Font("aakar", 1, 24)); // NOI18N
        appinted_vaccinee_btn.setForeground(new java.awt.Color(255, 255, 255));
        appinted_vaccinee_btn.setText("Appointed Vaccinee");
        appinted_vaccinee_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        appinted_vaccinee_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        appinted_vaccinee_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appinted_vaccinee_btnActionPerformed(evt);
            }
        });
        left_panel.add(appinted_vaccinee_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 390, 50));

        schedule_vaccination_btn.setBackground(new java.awt.Color(150, 150, 255));
        schedule_vaccination_btn.setFont(new java.awt.Font("aakar", 1, 24)); // NOI18N
        schedule_vaccination_btn.setForeground(new java.awt.Color(255, 255, 255));
        schedule_vaccination_btn.setText("Schedule Appointment Slots");
        schedule_vaccination_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        schedule_vaccination_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        schedule_vaccination_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schedule_vaccination_btnActionPerformed(evt);
            }
        });
        left_panel.add(schedule_vaccination_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 390, 50));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cowin_small.jpg"))); // NOI18N
        left_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 240));

        getContentPane().add(left_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 740));

        top_panel.setBackground(new java.awt.Color(102, 102, 255));
        top_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("aakar", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        top_panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 10, -1, -1));

        logout_btn.setBackground(new java.awt.Color(206, 17, 17));
        logout_btn.setFont(new java.awt.Font("aakar", 1, 24)); // NOI18N
        logout_btn.setForeground(new java.awt.Color(255, 255, 255));
        logout_btn.setText("LogOut");
        logout_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logout_btn.setBorderPainted(false);
        logout_btn.setFocusPainted(false);
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });
        top_panel.add(logout_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, 190, 60));

        getContentPane().add(top_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 1240, 100));

        bottom_panel.setBackground(new java.awt.Color(255, 255, 255));
        bottom_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        schedule_appointment_slot_panel.setBackground(new java.awt.Color(150, 150, 255));
        schedule_appointment_slot_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("aakar", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Schedule Appointment Slot");
        schedule_appointment_slot_panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1120, 60));

        jLabel9.setFont(new java.awt.Font("aakar", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("_____________________________________________________________");
        schedule_appointment_slot_panel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1120, -1));

        jLabel3.setFont(new java.awt.Font("aakar", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Vaccination Date:");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        schedule_appointment_slot_panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 210, 40));

        jLabel5.setFont(new java.awt.Font("aakar", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Vaccine Slot:");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        schedule_appointment_slot_panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 210, 40));

        submit_btn.setBackground(new java.awt.Color(10, 190, 46));
        submit_btn.setFont(new java.awt.Font("aakar", 1, 24)); // NOI18N
        submit_btn.setForeground(new java.awt.Color(255, 255, 255));
        submit_btn.setText("Submit");
        submit_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        submit_btn.setBorderPainted(false);
        submit_btn.setFocusPainted(false);
        submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btnActionPerformed(evt);
            }
        });
        schedule_appointment_slot_panel.add(submit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 190, 60));

        cancel_btn.setBackground(new java.awt.Color(206, 17, 17));
        cancel_btn.setFont(new java.awt.Font("aakar", 1, 24)); // NOI18N
        cancel_btn.setForeground(new java.awt.Color(255, 255, 255));
        cancel_btn.setText("Cancel");
        cancel_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancel_btn.setBorderPainted(false);
        cancel_btn.setFocusPainted(false);
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });
        schedule_appointment_slot_panel.add(cancel_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, 190, 60));

        vac_date.setBackground(new java.awt.Color(255, 255, 255));
        vac_date.setForeground(new java.awt.Color(150, 150, 255));
        vac_date.setDateFormatString("d-MM-yyyy");
        vac_date.setFont(new java.awt.Font("aakar", 1, 20)); // NOI18N
        schedule_appointment_slot_panel.add(vac_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 400, 40));

        vac_time.setBackground(new java.awt.Color(255, 255, 255));
        vac_time.setFont(new java.awt.Font("aakar", 1, 20)); // NOI18N
        vac_time.setForeground(new java.awt.Color(150, 150, 255));
        vac_time.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Slot", "09:00-12:00", "14:00-17:00" }));
        schedule_appointment_slot_panel.add(vac_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 400, 40));

        bottom_panel.add(schedule_appointment_slot_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 1150, 560));

        appointed_vaccinee_panel.setBackground(new java.awt.Color(150, 150, 255));
        appointed_vaccinee_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        appointed_table.setFont(new java.awt.Font("aakar", 1, 20)); // NOI18N

        table_appointed.setBackground(new java.awt.Color(150, 150, 255));
        table_appointed.setFont(new java.awt.Font("aakar", 0, 20)); // NOI18N
        table_appointed.setForeground(new java.awt.Color(255, 255, 255));
        table_appointed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr.No", "First Name", "Last Name", "Aadhar_no", "Date", "Slot", "Vaccine_name", "Does1"
            }
        ));
        appointed_table.setViewportView(table_appointed);

        appointed_vaccinee_panel.add(appointed_table, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 1100, 100));

        jLabel10.setFont(new java.awt.Font("aakar", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Appointed Vaccinee");
        appointed_vaccinee_panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1120, 60));

        jLabel11.setFont(new java.awt.Font("aakar", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("_____________________________________________________________");
        appointed_vaccinee_panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1120, -1));

        jLabel4.setFont(new java.awt.Font("aakar", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Enter Aadhar No. :");
        appointed_vaccinee_panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 240, 40));

        find_btn.setBackground(new java.awt.Color(17, 188, 56));
        find_btn.setFont(new java.awt.Font("aakar", 1, 24)); // NOI18N
        find_btn.setForeground(new java.awt.Color(255, 255, 255));
        find_btn.setText("Find");
        find_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        find_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                find_btnActionPerformed(evt);
            }
        });
        appointed_vaccinee_panel.add(find_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 140, 150, 40));

        aadhar_no_find.setBackground(new java.awt.Color(150, 150, 255));
        aadhar_no_find.setFont(new java.awt.Font("aakar", 1, 20)); // NOI18N
        aadhar_no_find.setForeground(new java.awt.Color(255, 255, 255));
        aadhar_no_find.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        aadhar_no_find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aadhar_no_findActionPerformed(evt);
            }
        });
        appointed_vaccinee_panel.add(aadhar_no_find, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 410, 40));

        vaccinated_btn.setBackground(new java.awt.Color(17, 188, 56));
        vaccinated_btn.setFont(new java.awt.Font("aakar", 1, 24)); // NOI18N
        vaccinated_btn.setForeground(new java.awt.Color(255, 255, 255));
        vaccinated_btn.setText("Vaccinated");
        vaccinated_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        vaccinated_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaccinated_btnActionPerformed(evt);
            }
        });
        appointed_vaccinee_panel.add(vaccinated_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 460, 230, 50));

        vaccine_name.setBackground(new java.awt.Color(150, 150, 255));
        vaccine_name.setFont(new java.awt.Font("aakar", 1, 20)); // NOI18N
        vaccine_name.setForeground(new java.awt.Color(255, 255, 255));
        vaccine_name.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Vaccine Name", "COVISHILD", "COVAXIN", "SPUTNIK-V" }));
        vaccine_name.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        appointed_vaccinee_panel.add(vaccine_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 400, 40));

        jLabel6.setFont(new java.awt.Font("aakar", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Vaccine Name:");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        appointed_vaccinee_panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 210, 40));

        bottom_panel.add(appointed_vaccinee_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 1150, 560));

        getContentPane().add(bottom_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 1240, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Login.main(null);
    }//GEN-LAST:event_logout_btnActionPerformed

    private void submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btnActionPerformed
        // TODO add your handling code here:
        if(vac_date.getDate()==null|| vac_time.getSelectedItem().equals("Select Slot"))
        {
            JOptionPane.showMessageDialog(new javax.swing.JFrame(),"Please Enter all the fields Properly....","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            if(vapp.insertData(vac_date.getDate(),(String) vac_time.getSelectedItem()))
            {
                JOptionPane.showMessageDialog(new javax.swing.JFrame(),"Data Inserted Successfully...","SUCCESS",JOptionPane.INFORMATION_MESSAGE);
                vac_date.setDate(null);
                vac_time.setSelectedItem("Select Slot");
            }
            else
            {
                JOptionPane.showMessageDialog(new javax.swing.JFrame(),"Error While Inserting Data....","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_submit_btnActionPerformed

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
        // TODO add your handling code here:
        vac_date.setDate(null);
        vac_time.setSelectedItem("Select Slot");
        
    }//GEN-LAST:event_cancel_btnActionPerformed

    private void appinted_vaccinee_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appinted_vaccinee_btnActionPerformed
        // TODO add your handling code here:
        schedule_appointment_slot_panel.setVisible(false);
        appointed_vaccinee_panel.setVisible(true);
                
    }//GEN-LAST:event_appinted_vaccinee_btnActionPerformed

    private void aadhar_no_findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aadhar_no_findActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aadhar_no_findActionPerformed

    private void find_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_find_btnActionPerformed
        // TODO add your handling code here:
        if(aadhar_no_find.getText().equals(""))
        {
            JOptionPane.showMessageDialog(new javax.swing.JFrame(),"Please Enter all the fields Properly....","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            List<String[]> l = vapp.getAppointedVaccineeData(aadhar_no_find.getText());
            DefaultTableModel t_model = ( DefaultTableModel)table_appointed.getModel();
            for(String[] s : l)
            {
                t_model.addRow(s);
            }
            
            
//       ---- table data here --


        }
       
    }//GEN-LAST:event_find_btnActionPerformed

    
    
    
    private void vaccinated_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaccinated_btnActionPerformed
        // TODO add your handling code here:
        if(vaccine_name.getSelectedItem().equals("Select Vaccine Name"))
        {
            JOptionPane.showMessageDialog(new javax.swing.JFrame(),"Please Enter all the fields Properly....","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            int index = table_appointed.getSelectedRow();
            String aadhar_no = table_appointed.getValueAt(index, 3).toString();
            String date= table_appointed.getValueAt(index, 4).toString();
            String does1 = table_appointed.getValueAt(index, 7).toString();
            if(vapp.setVaccinatedReport((String)vaccine_name.getSelectedItem(),aadhar_no,does1,date))
            {
                JOptionPane.showMessageDialog(new javax.swing.JFrame(),"Successfully Updated Record...,","Success",JOptionPane.INFORMATION_MESSAGE);
                aadhar_no_find.setText("");
                DefaultTableModel t_model = ( DefaultTableModel)table_appointed.getModel();
                t_model.setRowCount(0);
            }
            else
            {
                JOptionPane.showMessageDialog(new javax.swing.JFrame(),"Error While Updating Record..\n Try after some time...","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        
        
    }//GEN-LAST:event_vaccinated_btnActionPerformed

    private void schedule_vaccination_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schedule_vaccination_btnActionPerformed
        // TODO add your handling code here:
        appointed_vaccinee_panel.setVisible(false);
        schedule_appointment_slot_panel.setVisible(true);
    }//GEN-LAST:event_schedule_vaccination_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vaccinator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vaccinator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vaccinator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vaccinator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               Vaccinator v = new Vaccinator();
               v.user_name = args[0];
               v.appointed_vaccinee_panel.setVisible(false);
               v.schedule_appointment_slot_panel.setVisible(true);
               v.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aadhar_no_find;
    private javax.swing.JButton appinted_vaccinee_btn;
    private javax.swing.JScrollPane appointed_table;
    private javax.swing.JPanel appointed_vaccinee_panel;
    private javax.swing.JPanel bottom_panel;
    private javax.swing.JButton cancel_btn;
    private javax.swing.JButton find_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel left_panel;
    private javax.swing.JButton logout_btn;
    private javax.swing.JPanel schedule_appointment_slot_panel;
    private javax.swing.JButton schedule_vaccination_btn;
    private javax.swing.JButton submit_btn;
    private javax.swing.JTable table_appointed;
    private javax.swing.JPanel top_panel;
    private com.toedter.calendar.JDateChooser vac_date;
    private javax.swing.JComboBox<String> vac_time;
    private javax.swing.JButton vaccinated_btn;
    private javax.swing.JComboBox<String> vaccine_name;
    // End of variables declaration//GEN-END:variables
}
